version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/react_comedy_store'
      - '/react_comedy_store/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development